galaxy_info:
  author: Sean Myers
  description: Cloud DNS Management for OCP 4 clusters
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8

  galaxy_tags:
    - oasis

dependencies: []
