- name: Create destination directory for AWS Credentials
  file:
    state: directory
    dest: "{{ ocp_install_aws_creds_dest | dirname }}"

- name: Install AWS Credentials for openshift-install
  copy:
    src: "{{ ocp_install_aws_creds_file }}"
    dest: "{{ ocp_install_aws_creds_src }}"
