- name: Create OCP installer working dir
  file:
    state: directory
    path: "{{ ocp_install_config_dir }}"

- name: Generate OCP installer configuration
  template:
    src: "{{ ocp_install_config_template }}"
    dest: "{{ ocp_install_config_dir }}/install-config.yaml"
