dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: ocp_client_install
    image: centos:7
    ## Remove 'image' above and uncomment the following to run systemd in Docker
    # image: centos/systemd
    # privileged: true
    # command: /usr/lib/systemd/systemd --system
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: testinfra
  options:
    # Add a -v so you see the individual test names,
    # particularly useful with parameterized tests
    v: true
  lint:
    name: flake8
