driver:
  name: containers
platforms:
  - name: ocp_install
    image: centos:7
provisioner:
  playbooks:
    converge: playbook.yml
  config_options:
    defaults:
      ansible_managed: Custom ansible_managed string for testing
