- name: Run openshift-install create manifests
  command: >-
    {{ ocp_install_path }}/openshift-install create manifests
    --dir "{{ ocp_install_config_dir }}"
    --log-level "{{ ocp_install_log_level }}"
  when: ocp_install_create_manifests
