- name: Create destination directory for Azure Credentials
  file:
    state: directory
    dest: "{{ ocp_install_azure_creds_dest | dirname }}"
    mode: u+rx

- name: Install Azure Credentials for openshift-install
  copy:
    src: "{{ ocp_install_azure_creds_file }}"
    dest: "{{ ocp_install_azure_creds_src }}"
    mode: u+r
