- name: Create destination directory for Openstack Credentials
  file:
    state: directory
    dest: "{{ ocp_install_openstack_creds_dest | dirname }}"
    mode: u+rx

- name: Install Openstack Credentials for openshift-install
  copy:
    src: "{{ ocp_install_openstack_creds_file }}"
    dest: "{{ ocp_install_openstack_creds_src }}"
    mode: u+r
