name: Test with Ansible

"on":
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - galaxy.yml
      - AUTHORS
      - .github/labels.yml
      - .github/release-drafter.yml
  pull_request:
  schedule:
    - cron: "12 0 * * *"
  release:
    types:
      - published  # It seems that you can publish directly without creating
      - prereleased
  workflow_dispatch:

env:
  ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/:~/work/
  checkout_path: ansible_collections/oasis_roles/ocp

jobs:
  collect:
    runs-on: ubuntu-latest
    outputs:
      scenarios: "${{ steps.collection.outputs.tox-envs }}"
      vagrant_scenarios: "${{ steps.vagrant.outputs.tox-envs }}"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          set -ex
          python -m pip install --upgrade tox
      - id: collection
        uses: greg-hellings/tox-list@v1
        with:
          tox-args: --ansible-driver docker --ansible-driver podman --ansible-driver containers
      - id: vagrant
        uses: greg-hellings/tox-list@v1
        with:
          tox-args: --ansible-driver vagrant

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          path: "${{ env.checkout_path }}"
      - name: Update submodules to latest
        run: |
          cd "${{ env.checkout_path }}"
          git submodule update --remote --recursive
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          set -ex
          python -m pip install --upgrade tox
      - name: Run lint
        run: |
          cd "${{ env.checkout_path }}"
          tox -e lint_all

  vagrant_build:
    needs:
      - collect
      - lint
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        scenario: "${{ fromJson(needs.collect.outputs.vagrant_scenarios) }}"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          path: "${{ env.checkout_path }}"
      - name: Update submodules to latest
        run: |
          cd "${{ env.checkout_path }}"
          git submodule update --remote --recursive
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install -U tox
      - name: Cache/uncache Vagrant boxen
        id: scenario
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const scenario = '${{ matrix.scenario }}'.split('-').pop();
            return scenario;
      - name: Cache/uncache Vagrant boxen
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: "vagrant-${{ steps.scenario.outputs.result }}"
      - name: "Run tox against ${{ matrix.scenario }}"
        run: |
          set -ex
          mv ansible_collections ~/work/
          cd "~/work/${{ env.checkout_path }}"
          tox -e "${{ matrix.scenario }}"

  build:
    needs:
      - collect
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario: "${{ fromJson(needs.collect.outputs.scenarios) }}"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          path: "${{ env.checkout_path }}"
      - name: update submodules
        run: |
          cd "${{ env.checkout_path }}"
          git submodule update --remote --recursive
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          set -ex
          python -m pip install --upgrade tox
      - name: Run tox against "${{ matrix.scenario }}"
        run: |
          set -ex
          # There is some magic in the "mv" command that makes ansible-galaxy work
          # I haven't found any logic for it, but if you don't do this mv, then
          # the dependency step in molecule when run from tox will fail
          mv ansible_collections ~/work/
          cd "~/work/${{ env.checkout_path }}"
          tox -e "${{ matrix.scenario }}"

  release:
    needs:
      - build  # Only release if the build is good
      - vagrant_build
    if: github.event_type == 'release'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: artis3n/ansible_galaxy_collection@v2.6.2
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"
